function(protodd_validate_feature_rules registry_path)
    file(READ "${registry_path}" registry_json)
    string(JSON registry_schema ERROR_VARIABLE schema_error GET "${registry_json}" schema)
    if(schema_error OR NOT registry_schema STREQUAL "protodd-feature-registry-v1")
        message(FATAL_ERROR "Missing or unsupported Protodd feature registry: ${registry_path}")
    endif()

    string(JSON rule_count ERROR_VARIABLE rules_error LENGTH "${registry_json}" configuration_rules)
    if(rules_error)
        message(FATAL_ERROR "Feature registry has no configuration rules: ${rules_error}")
    endif()
    if(rule_count EQUAL 0)
        return()
    endif()
    math(EXPR last_rule "${rule_count} - 1")
    foreach(rule_index RANGE 0 ${last_rule})
        string(JSON trigger GET "${registry_json}" configuration_rules ${rule_index} when)
        string(JSON message_text GET "${registry_json}" configuration_rules ${rule_index} message)
        if(${trigger})
            string(JSON required_count LENGTH "${registry_json}" configuration_rules ${rule_index} requires_all)
            if(required_count GREATER 0)
                math(EXPR last_required "${required_count} - 1")
                foreach(required_index RANGE 0 ${last_required})
                    string(JSON required GET "${registry_json}" configuration_rules ${rule_index} requires_all ${required_index})
                    if(NOT ${required})
                        message(FATAL_ERROR "${message_text}")
                    endif()
                endforeach()
            endif()

            string(JSON alternative_count LENGTH "${registry_json}" configuration_rules ${rule_index} requires_any)
            if(alternative_count GREATER 0)
                set(any_alternative_enabled OFF)
                math(EXPR last_alternative "${alternative_count} - 1")
                foreach(alternative_index RANGE 0 ${last_alternative})
                    string(JSON alternative GET "${registry_json}" configuration_rules ${rule_index} requires_any ${alternative_index})
                    if(${alternative})
                        set(any_alternative_enabled ON)
                    endif()
                endforeach()
                if(NOT any_alternative_enabled)
                    message(FATAL_ERROR "${message_text}")
                endif()
            endif()

            string(JSON conflict_count LENGTH "${registry_json}" configuration_rules ${rule_index} conflicts)
            if(conflict_count GREATER 0)
                math(EXPR last_conflict "${conflict_count} - 1")
                foreach(conflict_index RANGE 0 ${last_conflict})
                    string(JSON conflict GET "${registry_json}" configuration_rules ${rule_index} conflicts ${conflict_index})
                    if(${conflict})
                        message(FATAL_ERROR "${message_text}")
                    endif()
                endforeach()
            endif()
        endif()
    endforeach()
endfunction()
